// JavaScript Document
define({ //dedine闭包
    indexLeft:[
        {appid:"pj",appname:"评价",href:"xsb_demo/zhpj/html/00stu_rcpj.html",appicon:"pj.png",appclass:""},
        {appid:"cj",appname:"学业",href:"xsb_demo/zhpj/html/00stu_sysp.html",appicon:"cj.png",appclass:""},
        {appid:"yd",appname:"运动",href:"xsb_demo/zhpj/html/00stu_tzjk.html",appicon:"yd.png",appclass:""},
        {appid:"ry",appname:"荣誉",href:"xsb_demo/zhpj/html/00stu_grry.html",appicon:"ry.png",appclass:""},
        {appid:"hd",appname:"活动",href:"xsb_demo/zhpj/html/00stu_sjhd.html",appicon:"hd.png",appclass:""},
        {appid:"czda",appname:"成长档案",href:"xsb_demo/zhpj/html/00stu_ccda.html",appicon:"czda.png",appclass:""}
    ],
    indexRight:[
        {appid:"gw",appname:"学校官网",href:"#",appicon:"gw.png",appclass:"w100"},
        //{appid:"zy",appname:"作业",href:"#",appicon:"zy.png",appclass:"w50"},
        {appid:"xk",appname:"选课",href:"xsb_demo/zxxk/1.1.xkjh(project_list)_M1109.html",appicon:"xk.png",appclass:"w50"},
        {appid:"dekt",appname:"第二课堂",href:"xsb_demo/dekt/parent-html/01course-c.html",appicon:"dekt.png",appclass:"w50"}
    ],
    school:[
        {appid:"kq",appname:"考勤",href:"xsb_demo/xskq/index_stu.html",appicon:"kq.png",appclass:""},
        //{appid:"xk",appname:"选课",href:"xsb_demo/zxxk/1.1.xkjh(project_list)_M1109.html",appicon:"xk.png",appclass:""},
        {appid:"kb",appname:"课表",href:"xsb_demo/zxkb/pk_sys2_stu.html",appicon:"kb.png",appclass:""},
        {appid:"xl",appname:"校历",href:"xsb_demo/xl/index.html",appicon:"xl.png",appclass:""},
        {appid:"ss",appname:"宿舍",href:"xsb_demo/ssgl/index.html",appicon:"ss.png",appclass:""},
        //{appid:"ziy",appname:"资源",href:"#",appicon:"ziy.png",appclass:""},
        {appid:"ks",appname:"考试",href:"xsb_demo/kwgl/index_ksap(student).html",appicon:"ks.png",appclass:""},
        {appid:"kcpj",appname:"课程评价",href:"#",appicon:"kcpj.png",appclass:""},
        {appid:"wj",appname:"问卷",href:"#",appicon:"wj.png",appclass:""},
        {appid:"jc",appname:"订餐",href:"xsb_demo/jcgl/index.html",appicon:"jc.png",appclass:""}
    ],
    other:[
        {appid:"jysd",appname:"教育商店",href:"EDstore/",appicon:"app.png",appclass:""},
        {appid:"yzt",appname:"语智通",href:"#",appicon:"yzt.png",appclass:""},
        {appid:"efd",appname:"E辅导",href:"#",appicon:"efd.png",appclass:""},
        {appid:"czbs",appname:"成长帮手",href:"http://czbspc.qk100.com/web",appicon:"czbs.png",appclass:""}
    ] 
});