// JavaScript Document
define({ //dedine闭包
    indexLeft:[
        {appid:"pj",appname:"评价",href:"#",appicon:"pj.png",appclass:""},
        {appid:"cj",appname:"成绩",href:"#",appicon:"cj.png",appclass:""},
        {appid:"yd",appname:"运动",href:"#",appicon:"yd.png",appclass:""},
        {appid:"ry",appname:"荣誉",href:"#",appicon:"ry.png",appclass:""},
        {appid:"hd",appname:"活动",href:"#",appicon:"hd.png",appclass:""},
        {appid:"czda",appname:"成长档案",href:"#",appicon:"czda.png",appclass:""}
    ],
    indexRight:[
        {appid:"gw",appname:"学校官网",href:"#",appicon:"gw.png",appclass:"w100"},
        {appid:"zy",appname:"作业",href:"#",appicon:"zy.png",appclass:"w50"},
        {appid:"dekt",appname:"第二课堂",href:"#",appicon:"dekt.png",appclass:"w50"}
    ],
    school:[
        {appid:"kq",appname:"考勤",href:"#",appicon:"kq.png",appclass:""},
        {appid:"xk",appname:"选课",href:"#",appicon:"xk.png",appclass:""},
        {appid:"ss",appname:"宿舍",href:"#",appicon:"ss.png",appclass:""},
        {appid:"ziy",appname:"资源",href:"#",appicon:"ziy.png",appclass:""},
        {appid:"ks",appname:"考试",href:"#",appicon:"ks.png",appclass:""},
        {appid:"kb",appname:"课表",href:"#",appicon:"kb.png",appclass:""},
        {appid:"xl",appname:"校历",href:"#",appicon:"xl.png",appclass:""},
        {appid:"kcpj",appname:"课程评价",href:"#",appicon:"kcpj.png",appclass:""},
        {appid:"wj",appname:"问卷",href:"#",appicon:"wj.png",appclass:""},
        {appid:"jc",appname:"就餐",href:"#",appicon:"jc.png",appclass:""}
    ],
    other:[
        {appid:"jysd",appname:"教育商店",href:"EDstore/",appicon:"app.png",appclass:""},
        {appid:"yzt",appname:"语智通",href:"#",appicon:"yzt.png",appclass:""},
        {appid:"efd",appname:"E辅导",href:"#",appicon:"efd.png",appclass:""},
        {appid:"czbs",appname:"成长帮手",href:"#",appicon:"czbs.png",appclass:""}
    ] 
});